version: 2.1
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    machine: true
      steps:
        -checkout
        - run:
            name: "Pull Submodules"
            command: |
              git submodule init
              git submodule update --remote
        - run:
            name: Build the REDCap image
            command: |
                cd redcap-docker-compose/rdc
                docker-compose up -d

  test:  
    - cypress/run:
        requires:
          - cypress/install
        steps:  
          - run:
              name: Run Cypress tests
              command: |
                  cd /root/project
                  mv cypress.json.example cypress.json
                  npm ci
                  npx cypress run

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build                    