version: 2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build the REDCap image
          command: |
            cd redcap-docker-compose/rdc
            docker-compose up -d
      - run:
          name: Install cypress
          command: |
            cd /home/circleci/project
            mv cypress.json.example cypress.json
            mv cypress.env.json.example cypress.env.json
            npm install
            npx cypress run --record --key a83f6d74-8a55-416c-87ba-8a3ed6e81b3b