version: 2

jobs:
  build:
    docker:
      - image: bayesimpact/circleci
      - image: cypress/base:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the REDCap image
          command: |
              cd redcap-docker-compose/rdc
              set -x
              docker-compose up -d
      - run:
          name: Run the E2E tests
          command: npm run test-multiple
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build