version: 2.0
orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build the REDCap image
          command: |
              cd redcap-docker-compose/rdc
              docker-compose up -d

workflows:
  version: 2
  build_and_test:
    jobs:
      - build