version: 2

jobs:
  test:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run:
        name: Build the REDCap image
        command: |
            set -x
            docker-compose up -d
      - run:
          name: Run the E2E tests
          command: npm run test-multiple

workflows:
  version: 2
  build_and_test:
    jobs:
      - test