version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: |
            sudo apt-get update
            sudo apt-get install mysql-client-core-8.0
      - run:
          name: Build the REDCap Image
          command: |
            git clone --branch redcap-cypress https://github.com/aldefouw/redcap_docker
      - run:
          name: Get REDCap Source
          command: |
            git clone --branch redcap-cypress https://github.com/aldefouw/redcap_source www
      - run:
          name: Start Docker REDCap Container
          command: |
            cd /home/circleci/project/redcap_docker
            docker-compose up -d --build
      - run:
          name: Change eDocs folder permissions
          command: |
            sudo chmod 777 /var/edocs
      - run:
          name: Configure Cypress environment
          command: |
            cd /home/circleci/project
            sed s/PID/$PROJECT_ID/g cypress.json.example > cypress.json
            mv cypress.env.json.example cypress.env.json              
      - run: mkdir ~/junit
      - run:
          name: Install Cypress
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use stable
            npm install
      - run:
          name: Run Tests
            TEST=$(circleci tests glob **/cypress/integration/core/*.js | circleci tests split --split-by=timings)
            npm test $TEST --record --key $RECORD_KEY
      - run:
          name: JUnit timing data
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        context: REDCap Tests