version: 2

jobs:
  test:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build the REDCap image
          command: |
              set -x
              docker-compose up -d
      - run:
          name: Run the E2E tests
          command: npm run test-multiple

workflows:
  version: 2
  build_and_test:
    jobs:
      - test